version: '3.1'

services:
  mongodb:
    image: mongo
    container_name: cursonodejs.mongodb
    restart: always
    ports: 
      - "27017:27017"

  node:
    build: .
    container_name: cursonodejs.node
    ports:
      - "3000:3000"
    depends_on: 
      - mongodb
    links:
      - mongodb